# Generated by Django 4.2.6 on 2023-12-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_descriptions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=200)),
                ('desc', models.CharField(max_length=200)),
                ('gallery_id', models.PositiveIntegerField()),
            ],
        ),
    ]
